name: Build Solr website with ASF Pelican action for PRs

on:
  pull_request:
    branches:
      - '**'

jobs:
  build-pelican:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Pelican Site
        uses: apache/infrastructure-actions/pelican@main
        with:
          destination: ${{ github.ref == 'refs/heads/production' && 'asf-site' || 'asf-staging' }}
          gfm: 'false'
          version: '4.8.0'
          publish: 'false'
